#!/bin/sh

MPATH=$(dirname $0)
FILE="$*"
FOLDER="${FILE%.*}"
echo "Folder: ${FOLDER}"
$MPATH/apktool/apktool d -f "${FILE}"
mkdir "${FOLDER}/src"
mv "${FOLDER}/smali" "${FOLDER}/.smali"
$MPATH/jadx/bin/jadx -d "${FOLDER}/src" "${FILE}"
